### ISSUE TITLE
我在python3环境下运行提示 string indices must be integers

### ISSUE THREAD

**Issue by sxiaoyuer** [lijinzhuang/gitlabanalyse#3]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    projects = git.getAllProjects()
  File "/devops/shell/gitlabanalyse/gitlabUtil.py", line 25, in getAllProjects
    pros = get100Projects(page)
  File "/devops/shell/gitlabanalyse/gitlabUtil.py", line 13, in get100Projects
    project['id'] = i['id']
TypeError: string indices must be integers

**Comment by yexiaobai** [comment]
我也遇到相同的问题

**Comment by yexiaobai** [comment]
不是python版本的问题，是gitlab api版本的问题
我的gitlab是20年安装的，版本不详，不支持/api/v3/projects接口

gitlabUtil.py
r = requests.get(
        private_host + '/api/v3/projects?private_token=' + private_token + '&per_page=100' + '&page=' + str(page))
改成/api/v4/projects

原作者的脚本稍微改改就能用
